name: Daily Report Generator

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  build-and-generate-report:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

     
      - name: Run the report generation script
        run: python backend/run_model.py

      - name: Commit and push files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate reports"
          file_pattern: "*.csv *.html"
